spring:
  application:
    name: FlashCards
  profiles:
    active: UpperCase
  datasource:
    url: jdbc:h2:file:./data/MyTryDB;DATABASE_TO_UPPER=false
    username: sa
    password:
  h2:
    console:
      path: /my-h2-db
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql-data/basic_entry.sql
      mode: always